### ISSUE TITLE
Scheme of device

### ISSUE THREAD

**Issue by Ryoko** [derryx/NexstarMountLib#1] opened 2016-07-25 23:22 UTC
Hi Derryx,

Great project. I'm trying to make something like this. I've really tired of entering date and time every time I'm starting my scope. But it's really hard to find celestron GPS in my country. So, the easyest way - made it by myself! :)))

I can't understand how you connect gps and mount to arduino. AFAIU, you connected gps to default serial of arduino (pins 0,1) but why do you using 2 software serial ports to connect mount? And how? Are they are connected in parallel? So one is used to recive and another to transmit message? 

And one more question: where do you connect arduino to mount. To AUX port of mount (TTL) or to RS232 port in handle?

So, can you, please, provide scheme of connection?

Thank you in advance!

**Comment by iflyhigh** [comment] 2016-07-26 09:36
Hi Ryoko,

GPS should be connected to pins 0 and 1 (HW serial on Atmega 328 etc). 2 software serial instances are used to connect to RD and TD pins in AUX port of the telescope and to control the scope by sending commands to it (and reading scope responses). Because of programmatic difficulties it's hard to implement the control code with a single SoftwareSerial instance thus Derryx have used two: one for sending, another one - for receiving. However, depending on a scope model there can be significant differences in a way this AUX port is working. For example, on my NexStar 5SE the CTS and RTS pins are unused (not connected at all) and RD and TD are connected together. Older NexStar models seem to have CTS and RTS functional.  You can also check my fork (works fine with 5SE) at https://github.com/iflyhigh/NexStarGPS where I've used somewhat simpler and cleaner code approach.

**Comment by derryx** [comment] 2016-07-26 12:56
Hi Ryoko,

My solution is connected to the AUX port which uses 5V TTL level and provides 12V for power.
The two serial devices are necessary because one talks to the GPS module and one to the mount. I connected the GPS module to the hardware serial-device because the hardware serial device can reach higher data rates. My GPS module is running at 38400 bps. I was not able to have a reliable connection with a soft serial device.
All the devices on the AUX port (including the hand-control) need to go to a high impedance state when they don't want to send something (search for tristate on Goolge).
I put my code on Github so that others can base on my experiments. I don't provide a full-blown solution. I can only tell you that my device works with my mount. On my mount CTS and RTS are working as expected so I toggle this pins as well. iflyhigh pointed out that this might not be necessary for newer devices.

**Comment by vic4hub** [comment] 2016-07-26 23:36
First of all, @derryx thank you so much for posting this!!
I, like @Ryoko have a similar problem - I too have purchased a cheap gps shield for my UNO and am trying to get this working. I am a newbie to electronics and own Celestrone 102 SLT, which I am thus unsuccessful at hacking using instructions from: 

https://sites.google.com/site/wayneholder/nexstar-direct-telescope-mount-control 
and: 
https://sites.google.com/site/wayneholder/nexstartm-direct-telescope-mount-control---revisited

Once I am able to get this to work, I plan to work on video recognition software to have the telescope follow and track objects in motion (satellites etc).

I wonder if any of you guys can provide me with any bits of knowledge to get this working, again very much appreciate your work and will share anything I accomplish back to the community.

**Comment by iflyhigh** [comment] 2016-07-27 06:36
vic4hub, most likely 102SLT uses the same protocol as other modern Celestron scopes. I'd suggest you buy a logic analyzer device (cheap ones (30-40$) from aliexpress works just fine) and try capturing data flow on AUX port to figure out what you are doing wrong. From my personal experience with 5SE the _almost_ correct code will cause hand controller initialization errors during boot or motor failure messages (false, cleared by powercycling) if you try to move a tube by pressing buttons on a hand controller :) There is no magic behind this serial communication protocol, just weirdness.

**Comment by derryx** [comment] 2016-07-27 08:44
Just to be sure that you know it:

http://www.paquettefamily.ca/nexstar/NexStar_AUX_Commands_10.pdf

describes not only the GPS commands but also the motor commands.

**Comment by Ryoko** [comment] 2016-07-27 17:00
Hi Derryx, Iflyhigh,

Thanks for your answers!

Derryx, I've understand, that this is your solution, worked on your mount, and you don't provide solution for all devices. You share this solution with us, and I'm really grateful for it! I'm trying to understand how it must work, so I can understand - how can I apply it to my mount.

Can I ask some more questions, if you do not mind?

So to summarize all:
- GPS is connected to standart serial pins of arduino (it was obvious from code)
- Two instances of softwareserials are used to organize message exchange with mount.
- RX_PIN and TX_PIN are used for recive data from AUX
- RX2_PIN and TX2_PIN are used for transmit data to AUX
  
So the questions are:
- Does TX_PIN and RX2_PIN need to be connected at all? And if they need to be connected, than how? Are we just connect both RX and RX2 pins to data_from_main and both TX and TX2 to data_from_device? 
- My mount (CG-5 GT) have only one additional signal - RTS. And, from what I've seen, I asume, that RX and TX signals are somehow shortcuted inside the mount. My analyzer shows same signals in both RX and TX lines. How do you think, am I need to change something in code or it will work as is?

@iflyhigh I've look through your fork. And will try it on my mount as well. In your fork used two pins to RX and TX and it easier to understand how it must be connected. And it seems that we have same thing with TX and RX logicaly shortcuted in mount. But are you sure, that your RTS signal is not worked at all? Couse it may case some issues with signal overlapping...

**Comment by vic4hub** [comment] 2016-07-27 23:35
@iflyhigh / @derryx thanks for that, I do have a similar question to @Ryoko - as to whether you guys had to add any additional logic circuits or the entire hookup was directly to arduino lines w/o any resistors etc. and the whole tristate process was somehow accomplished using software only?

@iflyhigh I did get to the state you are describing, where the thing is freaking out with erros - I wonder if it would not be too difficult for you to post pins from yours (pic may be enough) - with labels as to what they are. Thank you.

**Comment by Ryoko** [comment] 2016-07-28 01:16
I've managed to almoust launch @iflyhigh fork of this project. Arduino can talk with mount but don't want to provide GPS info yet. Maybe protocol in my mount slightly different. I will check it later. But mount talks with arduino and it's really nice. 

Also I found a small bug. For my mount at least. I've create pull request with fix. This bug can be issue with "Can't initialize motor driver";

**Comment by vic4hub** [comment] 2016-07-28 02:18
@Ryoko - well don't hold back! How did u get it work? A picture perhaps?

**Comment by Ryoko** [comment] 2016-07-28 12:38
@vic4hub 
It's quite simle. I just connect RX_PIN (3 by default) to data_from_main (pin 2 in RJ-12) and TX_PIN (5 by default) to data_from_device (pin 4 in RJ-12). And of cource GND from GND on arduino to GND of mount (pin 5 in RJ-12). And this is all. Also I've comment to lines in code to prevent pullup of RX signal. You can use my fork here [https://github.com/Ryoko/NexStarGPS](url)
![image](https://cloud.githubusercontent.com/assets/475943/17212673/4cc29e1e-54d9-11e6-9701-65393bce37ca.png)

**Comment by vic4hub** [comment] 2016-07-28 14:13
@Ryoko that is perfect and dead simple! I shall try that out today on my SLT! Thank you!

**Comment by vic4hub** [comment] 2016-07-29 14:33
I still can't get it to work using @iflyhigh's code - I got 3 pins from the scope confirmed returning close to 5v and one ground, I have gps all set and even added an LED light! After trying rearranging 3 pins in every combination (6 possible, 3 factorial) - In two cases I get mountserial.available() to be true and mountserial.read() returning a zero - don't know what else there is I can do... Anyone?

**Comment by iflyhigh** [comment] 2016-07-29 16:35
@vic4hub, buy a logic analyzer. It's really hard to reverse engineer any kind of digital interface without such a very basic tool... You can also try capturing data on AUX port, you shoud see correct Celestron protocol data (@derryx have posted a link for it).

When I've been struggling with my 5SE I've noticed that the critical part of the code is a tri-state port logic. My setup does not use any external resistors, just internal Atmega pull-ups. YMMV.

**Comment by Ryoko** [comment] 2016-08-02 11:22
@vic4hub try my fork. In @iflyhigh code there is a little issue in ross.cpp that prevent it from working on my mount. The signal line is pulled up by code and this mess with data reading. In my fork ([https://github.com/Ryoko/NexStarGPS](url)) I've fixed it.

**Comment by Ryoko** [comment] 2016-08-03 02:26
@vic4hub I was wrong about previouse changes in code. It wasn't needed. 
But now I've really found some protocol bugs. Fixed it and finaly get my mount working with GPS.
I've updated my fork with this changes. First bug was creating low signal value ~26ms before transmiting. Second was creating low signal value after transmiting. A few changes in code removes this low signals.

This low signals was quite short and some mounts would not messed with them. But for some mounts (my for examle) this signals prevents normal work.

**Comment by vic4hub** [comment] 2016-08-04 18:51
I've tried so many things at this point, that I've pretty much lost any faith in this - probably going to return this telescope too. Either way, thanks guys for sharing - hopefully this takes off a bit more with more models etc.

**Comment by derryx** [comment] 2016-08-09 08:36
Don't give up. It took me several weeks until I found out what was wrong. What has helped a lot was listening to what the hand control and the motor controller exchange.
I realised that two things where wrong:
# the ID of the GPS module my mount wanted to talk is different to that in the PDF
# I have to pull the serial line to a defined state before starting communication

**Comment by derryx** [comment] 2019-08-14 06:54
Closing this because there will be no update to this anymore

**Closed by derryx** 2019-08-14 06:54 UTC
